name: "research"

on:
  workflow_dispatch:

env:
  BUILD_DIR: '${{github.workspace}}/build'
  QT_VERSION_VPKEDIT: '6.6.3'
  QT_VERSION_STRATASOURCE: '6.5.3'
  QT_MODULES: 'qtimageformats'

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        compiler: [clang]
        target: [VPKEdit]
    runs-on: ubuntu-20.04
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Necessary Packages
        run: sudo apt update && sudo apt install -y cmake build-essential ninja-build chrpath

      - name: Install Clang [compiler:clang]
        if: ${{matrix.compiler == 'clang'}}
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64

      - name: Install Qt [target:VPKEdit]
        if: ${{matrix.target == 'VPKEdit'}}
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{env.QT_VERSION_VPKEDIT}}
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: '${{github.workspace}}/qt'
          modules: ${{env.QT_MODULES}}
          cache: true

      - name: Configure CMake [target:VPKEdit]
        if: ${{matrix.target == 'VPKEdit'}}
        run: cmake -G "Ninja" -B "${{env.BUILD_DIR}}" -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DQT_BASEDIR="${{github.workspace}}/qt/Qt/${{env.QT_VERSION_VPKEDIT}}/gcc_64" -DVPKEDIT_USE_LTO=ON

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: c-cpp
          queries: security-extended,security-and-quality

      - name: Build Binaries
        working-directory: '${{env.BUILD_DIR}}'
        run: |
          cmake --build . --config ${{matrix.build_type}} -t vpkeditcli -- -j$(nproc)
          cmake --build . --config ${{matrix.build_type}} -t vpkedit -- -j$(nproc)

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:c-cpp"
